{% set name = "httptools" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: abd72556974f8e7c74a259655924a717a2365b236c882c3f6f8a45fe94703ac9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools ==80.9.0
    - cython >=3.1.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - httptools
    - httptools.parser
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/MagicStack/httptools
  summary: Fast HTTP parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    httptools is a Python binding for the nodejs HTTP parser.
  doc_url: https://github.com/MagicStack/httptools
  dev_url: https://github.com/MagicStack/httptools

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - carlodri
