{% set name = "httptools" %}
{% set version = "0.6.4" %}
{% set sha256 = "4e93eee4add6493b59a5c514da98c939b244fce4a0d8879cd3f466562f4b7d5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.24
  run:
    - python

test:
  imports:
    - httptools
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MagicStack/httptools
  summary: Fast HTTP parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    httptools is a Python binding for the nodejs HTTP parser.
  doc_url: https://github.com/MagicStack/httptools
  dev_url: https://github.com/MagicStack/httptools

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - carlodri
